<?php
//define table name
define('ADMINISTRATORS',"administrators");
define('SUPERADMIN_PASSWORD','superadmin_password');
define('ADMIN_LEVELS',"admin_levels"); 
define('ADMIN_MODULES',"admin_modules"); 
define('LEVEL_TO_MODULES',"level_to_modules");
define('ZEEMO_RESOURCE','zeemo_resource');
define('PAGES',"pages");
define('COMMON_SETTINGS',"common_settings");
define('PAGE_HEADING',"page_heading");
define('TOP_TEXT','top_text');
define('META_TAGS','meta_tags');
define('META_SINGLE_PAGES','meta_single_pages');
define('LEAD_SOURCES','lead_sources');
define('STATIC_PAGE_URLS','static_page_urls');
define('LEADS','leads');
define('CTA','cta');
define('BLOG_NOTIFICATIONS',"blog_notifications");
define('CMS_SETTINGS','cms_settings');
define('EMAIL_MESSAGES',"email_messages");
define('AUTO_EMAIL_NOTIFICATION',"auto_email_notification");
define('ZEEMO_SETTINGS','zeemo_settings');
define('PROJECTS','projects');
define('SUPPORTS','supports');
define('ACCOUNT_TYPE','account_type');
define('CAMPAIGN_TYPE','campaign_type');
define('CAMPAIGN_IMAGES','campaign_images');
define('USERS','users');
define('CAMPAIGN_SETTINGS','campaign_settings');
define('USER_CAMPAIGNS','user_campaigns');
define('BIRTHDAY_PLEDGE','birthday_pledge');
define('DONATIONS','donations');
define('CAMPAIGN_COMMENTS','campaign_comments');

?>
